### ISSUE TITLE
Can't find plugin in WordPress directory

### ISSUE THREAD

**Issue by jacksegal** [mindtwo/post-duplicator-polylang#2]
I'm really excited by this plugin - I'm hoping it's going to fix our issue!

However I can't find it in the "WordPress Plugin Manager Search":

<img width="1320" alt="image" src="https://user-images.githubusercontent.com/9342782/174101260-a8f8882a-dec3-48d1-bb6f-755adb729309.png">

Am I missing something obvious here?  Or is it no longer available by the WP Plugin search?

If I install it locally by composer, can I just upload the files to my site?  Or does the install script do something else too?

Thanks again 💚

**Comment by jonasemde** [comment]
We don't use the plugin directory of WordPress in the Agency, and manage our dependencies with Composer.

But yes, of course you can just download it and put it in the plugin directory.

**Comment by jacksegal** [comment]
Thank you for clarifying @jonasemde - just a suggestion, but it might be worth updating the README to reflect that - it currently says you can search for it in the plugin directory.
